<?php


include_once('oauth.php');

//pesapal params
$token = $params = NULL;

/*
PesaPal Sandbox is at https://demo.pesapal.com. Use this to test your developement and 
when you are ready to go live change to https://www.pesapal.com.
*/
$consumer_key = 'BklkhHlqMXqA7QZf2b9mkZViA/hKPhBa';//Register a merchant account on
//demo.pesapal.com and use the merchant key for testing.
//When you are ready to go live make sure you change the key to the live account
//registered on www.pesapal.com!
$consumer_secret = 'u221ezUpDYQQkmzVcnfHJU+qJrs=';// Use the secret from your test
//account on demo.pesapal.com. When you are ready to go live make sure you
//change the secret to the live account registered on www.pesapal.com!
//account on demo.pesapal.com. When you are ready to go live make sure you 
//change the secret to the live account registered on www.pesapal.com!
$signature_method = new OAuthSignatureMethod_HMAC_SHA1();
$iframelink = //'https://demo.pesapal.com/api/PostPesapalDirectOrderV4'; //change to      
'https://www.pesapal.com/API/PostPesapalDirectOrderV4';// when you are ready to go live!

//get form details
$amount = $_POST['amount'];
$amount = number_format($amount, 2); //format amount to 2 decimal places

$desc = "Order";// $_POST['description'];
$type =  "MERCHANT"; //$_POST['type']; //default value = MERCHANT
$reference = $_POST['Order_id']; //unique order id of the transaction, generated by merchant
$first_name =  $_POST['first_name'];
$last_name =  $_POST['last_name'];
$email =  $_POST['email'];
$phonenumber = $_POST['phonenumber'];   //ONE of email or phonenumber is required
$currency = "USD";
$description ="Order";

$callback_url = 'localhost/index.com/redirect.php'; //redirect url, the page that will handle the response from pesapal.

$post_xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?>
                        <PesapalDirectOrderInfo
                            xmlns:xsi=\"http://www.w3.org/2001/XMLSchemainstance\"
                            xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"
                            Amount=\"" .$amount . "\"
                            Description=\"" . $description . "\"
                            Type=\"" . $type . "\"
                            Reference=\"" . $reference . "\"
                            FirstName=\"" . $first_name . "\"
                            LastName=\"" . $last_name . "\"
                            Currency=\"" . $currency . "\"
                            Email=\"" . $email . "\"
                            PhoneNumber=\"" . $phonenumber . "\"
                            xmlns=\"http://www.pesapal.com\">" .
            "</PesapalDirectOrderInfo>";


$post_xml = htmlentities($post_xml);

$consumer = new OAuthConsumer($consumer_key, $consumer_secret);

//post transaction to pesapal
$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
$iframe_src->set_parameter("oauth_callback", $callback_url);
$iframe_src->set_parameter("pesapal_request_data", $post_xml);
$iframe_src->sign_request($signature_method, $consumer, $token);

//display pesapal - iframe and pass iframe_src

?>
<iframe src="<?php echo $iframe_src; ?>" width="100%" height="700px" scrolling="no" frameBorder="0">
    <p>Browser unable to load iFrame</p>
</iframe>
